include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 85
  trailing_commas: preserve

analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_catches_without_on_clauses: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    no_literal_bool_comparisons: ignore
    no_runtimetype_tostring: ignore
    prefer_foreach: ignore
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - lib/brick/brick.g.dart
    - lib/brick/db/schema.g.dart
    - lib/**/*.graphql.dart
    - lib/schema.graphql.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: false
